### ISSUE TITLE
Boot strapping doesnot work.

### ISSUE THREAD

**Issue by aswins** [santhoshtr/pypdflib#6]
The file bootstrap.py contains the following error.

Traceback (most recent call last):
  File "bootstrap.py", line 116, in <module>
    ws.find(pkg_resources.Requirement.parse(requirement)).location
AttributeError: 'NoneType' object has no attribute 'location'

**Comment by santhoshtr** [comment]
https://bugs.launchpad.net/zc.buildout/+bug/410528

**Comment by santhoshtr** [comment]
The build is simplified now. use the new build instructions.
Closing this issue
